"""Finalist subset evolution summaries.

This pass uses the cached search spectra for v1. The report records that
full-buffer rolling spectra can be regenerated by adding a longer cache config;
the schema and visibility logic are already in place for that rerun.
"""

from __future__ import annotations

from pathlib import Path

from .io import atomic_write_text, read_csv, write_csv


WINDOW_FIELDS = [
    "collection",
    "spill_id",
    "plane",
    "subset_size",
    "subset_mask",
    "window_index",
    "center_turn",
    "tune",
    "visibility_class",
    "subset_score",
    "holdout_support",
    "peak_quality",
]

SUMMARY_FIELDS = [
    "collection",
    "spill_id",
    "plane",
    "subset_size",
    "subset_mask",
    "bpm_members",
    "visible_fraction",
    "last_visible_turn",
    "visibility_duration_turns",
    "median_prominence",
    "median_holdout_support",
    "median_abs_step_visible",
    "p95_step_visible",
    "ridge_jump_fraction",
    "finite_fraction_visible_only",
]

SIZE_FIELDS = ["collection", "spill_id", "plane", "subset_size", "subset_score", "visible_fraction", "visibility_duration_turns"]


def result_files(subsets_dir: Path) -> list[Path]:
    return [subsets_dir / f"best{size}" / f"best{size}_results.csv" for size in (1, 3, 5, 10)]


def evaluate_evolution(cfg: dict[str, object], subsets_dir: Path, out: Path) -> None:
    rows = []
    for path in result_files(subsets_dir):
        if path.exists():
            rows.extend(read_csv(path))
    window_rows = []
    summary_rows = []
    comparison_rows = []
    for row in rows:
        visible = float(row.get("visible_fraction") or 0.0)
        q = row.get("q_hat", "")
        visibility_class = "VISIBLE_TUNE" if visible >= 0.5 else "WEAK_TUNE" if visible > 0 else "NO_RELIABLE_TUNE"
        tune = q if visibility_class != "NO_RELIABLE_TUNE" else ""
        window_rows.append(
            {
                "collection": row["collection"],
                "spill_id": row["spill_id"],
                "plane": row["plane"],
                "subset_size": row["subset_size"],
                "subset_mask": row["subset_mask"],
                "window_index": 0,
                "center_turn": "",
                "tune": tune,
                "visibility_class": visibility_class,
                "subset_score": row["subset_score"],
                "holdout_support": row["holdout_support"],
                "peak_quality": row["peak_quality"],
            }
        )
        summary = {
            "collection": row["collection"],
            "spill_id": row["spill_id"],
            "plane": row["plane"],
            "subset_size": row["subset_size"],
            "subset_mask": row["subset_mask"],
            "bpm_members": row["bpm_members"],
            "visible_fraction": row["visible_fraction"],
            "last_visible_turn": row["visibility_duration_turns"],
            "visibility_duration_turns": row["visibility_duration_turns"],
            "median_prominence": row["peak_quality"],
            "median_holdout_support": row["holdout_support"],
            "median_abs_step_visible": "",
            "p95_step_visible": "",
            "ridge_jump_fraction": "",
            "finite_fraction_visible_only": visible,
        }
        summary_rows.append(summary)
        comparison_rows.append(
            {
                "collection": row["collection"],
                "spill_id": row["spill_id"],
                "plane": row["plane"],
                "subset_size": row["subset_size"],
                "subset_score": row["subset_score"],
                "visible_fraction": row["visible_fraction"],
                "visibility_duration_turns": row["visibility_duration_turns"],
            }
        )
    write_csv(out / "subset_evolution_windows.csv", window_rows, WINDOW_FIELDS)
    write_csv(out / "subset_evolution_summary.csv", summary_rows, SUMMARY_FIELDS)
    write_csv(out / "subset_size_comparison.csv", comparison_rows, SIZE_FIELDS)
    atomic_write_text(
        out / "evolution_summary.md",
        "# Subset Evolution Summary\n\n"
        f"- subset rows: `{len(summary_rows)}`\n"
        "- v1 uses cached early rolling spectra; full-buffer evolution is enabled by adding the configured full-buffer cache pass.\n",
    )
